INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (1,'小丑','2019-08-31','joker1.jpg','joker2.jpg','小丑预告.mp4','托德·菲利普斯','华金·菲尼克斯',1,1,1,'亚瑟·弗莱克是一个和母亲住在老旧公寓里，需要靠社会福利组织帮助，不断服用精神疾病药物的小丑。他想成为一个脱口秀演员，但并不成功。人们只是嘲笑他。他在地铁上爆发式地犯下了谋杀案。');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (2,'血战钢锯岭','2016-12-08','血战1.jpg','血战2.jpg','钢锯岭预告.mp4','梅尔·吉布森','安德鲁·加菲尔德 / 萨姆·沃辛顿',1,1,1,'在1942年的太平洋战场，军医戴斯蒙德·道斯（安德鲁·加菲尔德饰）不愿意在前线举枪射杀任何一个人，他因自己的和平理想遭受着其他战士们的排挤');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (3,'肖申克的救赎','1994-09-10','肖申克1.jpg','肖申克2.jpg','肖申克预告.mp4','弗兰克·德拉邦特','蒂姆·罗宾斯 / 摩根·弗里曼',1,1,1,'故事中，年轻的银行家安迪因为妻子和她的情人被杀而被判无期徒刑，由于监狱的腐败，他在真相即将大白的情况下仍然得不到昭雪，反而在肖申克监狱饱受了各种精神上和肉体上的摧残。');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (4,'千与千寻','2001-07-20','千寻1.jpg','千寻2.jpg','千与千寻预告.mp4','宫崎骏','柊瑠美 / 入野自由',1,1,1,'10岁的少女千寻与父母一起从都市搬家到了乡下。没想到在搬家的途中，一家人发生了意外。他们进入了汤屋老板魔女控制的奇特世界——在那里不劳动的人将会被变成动物。');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (5,'阿凡达','2009-12-18','阿凡达1.jpg','阿凡达2.jpg','','詹姆斯·卡梅隆','萨姆·沃辛顿 / 佐伊·索尔达娜',0,1,1,'该片主要讲述人类穿上阿凡达的躯壳，飞到遥远的星球潘多拉开采资源。受伤后以轮椅代步的前海军杰克，自愿接受实验并以他的阿凡达来到潘多拉。');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (6,'无间道','2002-12-12','无间道1.jpg','无间道2.jpg','无间道预告.mp4','刘伟强 / 麦兆辉','刘德华 / 梁朝伟 / 黄秋生',1,1,1,'该片讲述的是两个身份混乱的男人分别为警方和黑社会的卧底，经过一场激烈的角斗，他们决心要寻回自己的故事。');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (7,'寻梦环游记','2017-11-24','寻梦1.jpg','寻梦2.jpg','寻梦预告.mp4','李·昂克里奇 / 阿德里安·莫利纳','安东尼·冈萨雷斯 / 盖尔·加西亚·贝纳尔',0,1,1,'一个鞋匠家庭出身的12岁墨西哥小男孩米格，自幼有一个音乐梦，但音乐却是被家庭所禁止的，他们认为自己被音乐诅咒了。在米格秘密追寻音乐梦时，因为触碰了一把吉他而踏上了亡灵土地。');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (8,'变形金刚5','2017-06-23','变形金刚2.jpg','变形金刚1.jpg','变形金刚预告.mp4','迈克尔·贝','马克·沃尔伯格 / 伊莎贝拉·莫奈',1,0,1,'该片主要讲述了一个名叫山姆的青年，因机缘巧合而卷入了变形金刚中汽车人与霸天虎两派抢夺“火种”的战争之中，并与其他众人与汽车人联手打碎霸天虎征服世界野心的故事。');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (9,'环太平洋','2013-07-31','环太1.jpg','环太2.jpg','环太平洋预告.mp4','吉尔莫·德尔·托罗','查理·汉纳姆 / 菊地凛子',1,0,0,'该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。');
INSERT INTO `` (`FILM_ID`,`FILM_NAME`,`FILM_RELEASE_TIME`,`FILM_IMAGE_MAIN`,`FILM_IMAGE_OTHER`,`FILM_VIDEO_URL`,`FILM_DIRECTOR`,`FILM_PERFORMER`,`FILM_STATE`,`FILM_LEVEL`,`FILM_HOT`,`FILM_DESCRIPTION`) VALUES (10,'教父','1972-03-15','
